name: Integration tests

on:
  pull_request:
  push:
  schedule:
    # Run Monday morning at 3 o'clock
    #       ┌───────────── minute (0 - 59)
    #       │ ┌───────────── hour (0 - 23)
    #       │ │ ┌───────────── day of the month (1 - 31)
    #       │ │ │ ┌───────────── month (1 - 12)
    #       │ │ │ │ ┌───────────── day of the week (0 - 6)
    #       │ │ │ │ │
    #       │ │ │ │ │
    #       │ │ │ │ │
    - cron: 0 3 * * 1
  workflow_dispatch:

jobs:
  integration:
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]
        laravel: [^9.0, ^10.0]
        exclude:
          - php: 8.0
            laravel: ^10.0
    name: P=${{ matrix.php }} L=${{ matrix.laravel }}
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      # Due to version incompatibility with older Laravels we test, we remove it
      - run: composer remove --dev larastan/larastan --no-update
      - run: composer remove --dev friendsofphp/php-cs-fixer --no-update
      - run: composer require illuminate/contracts:${{ matrix.laravel }} --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --prefer-dist

      - run: tests/integration-laravel.sh ${{ matrix.laravel }}
